
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import { Suspense } from "react";
import { Spinner } from "@/components/spinner";
import '../app/globals.css';
import Home from './page';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col min-h-screen'>
        <Navbar/>
        <main className='flex-1'>{children}</main>
        <Footer/>
        </body>
    </html>
  )
}
